# 🚦 Person A / 🔄 Person F - Enhanced Docker Compose
version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017
    volumes:
      - ./app:/app/app
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
